# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_auto_20191011_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_authors_app.Author'),
        ),
    ]
