# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0005_auto_20191011_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
