# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-11 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0006_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(null=True, related_name='books', to='books_authors_app.Author'),
        ),
    ]
