# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-20 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0005_auto_20191020_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='login_register_app.User'),
        ),
    ]
