# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-17 15:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_app', '0002_show_release'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
                ('objectss', django.db.models.manager.Manager()),
            ],
        ),
    ]
