# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-17 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_app', '0003_auto_20191017_1527'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='show',
            managers=[
            ],
        ),
    ]
