# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_app', '0004_auto_20191017_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
