# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-30 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wall_app.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wall_app.Message'),
        ),
    ]
