# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20190730_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wall_app.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wall_app.Message'),
        ),
    ]
